### ISSUE TITLE
Guestbook post results in 500 Server Error - was missing guestbook SQL.

### ISSUE THREAD

**Issue by jjaimealeman** [kevinzunigacuellar/astro-supabase#5]
```
CREATE TABLE guestbook (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
```

I'm guessing this is what's needed?!

![image](https://github.com/kevinzunigacuellar/astro-supabase/assets/1428292/9313cdfb-b6d5-48d2-83ee-c30a137cd307)

It's working fine now ;)

**Comment by kevinzunigacuellar** [comment]
Thanks for raising an issue. I really appreciate the helpful comment.

While including the SQL to generate the guestbook table could be helpful for some, this demo was not meant to be copied as is but rather to serve as reference for building other Supabase apps. With that goal in mind, I don't believe adding the SQL would provide much benefit.

**Comment by akbar-pekat** [comment]
@jjaimealeman @kevinzunigacuellar Hi, could you provide the table format used in Supabase? However, I'm experiencing the same problem as mentioned here.

![image](https://github.com/user-attachments/assets/ea611d34-96e2-4ff3-aad3-48b8b4f987a8)
